### PR TITLE
Added new updated homepage with light copy changes, also added new asset...

### PR DESCRIPTION
**Pull request by rr1000**
Added new updated homepage with light copy changes, also added new asset structure.

Screen shot:

homepage_screen_shot

### CODE REVIEW

**Comment by rogerwang** [comment]
Thanks. The PR still contains unwanted files like the sass-cache despite gitignore has it?

**Comment by rr1000** [comment]
Yeah, looks like those got committed from before. They should be gone now.

**Comment by rogerwang** [comment]
when I open your PR locally to see it, it shows broken page.

**Comment by rr1000** [comment]
Are you running a local web server? If not you can simply run:

`python -m SimpleHTTPServer 8888`

**Comment by rogerwang** [comment]
Thanks. But the logo and the wording is not expected. Currently @dcohenb has been working on a new design and implementation.

**Pull request closed without merging**
