### PR TITLE
Complete overhaul of the new site

### PR DESCRIPTION
**Pull request by TheJaredWilcurt**
## Complete overhaul of the new site.

**NOTE:** *This version of the site is following the MVP principal* **(Minimal Viable Product).** *As such, the goal is to have a functioning, easy to update, but lightweight version that is updated and improved often.*

A live demo of the new version can be seen here:

* **[TheJaredWilcurt.github.io/website](http://TheJaredWilcurt.github.io/website)**

It is based off of a previous branch's design by [Daniel Cohen](https://github.com/dcohenb), the architecture and organization has been heavily modified and improved.

* * *

### Features of this new version:

* **GitHub.io hosting:**
 * This is important as it means that it this is a static website that can be updated directly on the GitHub website, allowing easier contributions from the community and no server maintanence.
 * I would ***highly*** suggest renaming the repo from `website` to the [official GitHub standard](https://help.github.com/articles/user-organization-and-project-pages/) `nwjs.github.io`. Followed by adding a `CNAME` file to the root of the repo to allow nwjs.io to [point to it properly](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages).
* **Dynamic content:**
 * The `api.json` file is a large JSON payload of the main versions of Node-Webkit and NW.js, including links to the downloads. Not only is this used by this website, but others could use it in their apps and sites as well.
 * The `config.json` file is a small JSON payload with specific information about the current recommended stable release of NW.js.
* **Modular content:**
 * The content for the **header** and **footer** that is used on every page are stored in the `_markup` folder. They are dynamically placed on page load so we only need to update this content in one location.
 * The content for the Quick Start page is stored as an easily editable markdown file. Other pages can have their content stored in this manner as well.
* **Navigation:**
 * The main navigation has been slimmed down to a more realistic set of pages. Home, Quickstart, Download, and Documentation. The Documentation currently links to the wiki, as it is the best resource, however we may be able to dynamically pull in the Wiki's content using GitHub's API in the future. I don't deem this MVP though being that the wiki works well enough for now. I removed the Blog from the navigation, as there is no blog currently, for NW.js. If someone wants to step up and be the author of one, we can implement a solution for that (there are several options). But for now, I'm assuming this is a feature that can be left to the Google Group. Though I'm not against having a prettier way of disseminating this information.
 * The footer navigation has also been updated to have more relavent content that links to appropriate locations, rather than the placeholders that were there initially in the design.
* **Responsive:**
 * All pages have had their CSS altered to allow for better displaying on smaller screens, such as phones.
* **404 and Simple URL Routing**:
 * There is now a 404 page that has a simple routing system built in that detects similar URLs that users may put in and auto-forwards them to the correct page. So URLs like `nwjs.io/dl` or `nwjs.io/downloads` will. automatically take you to `nwjs.io/download.html`.
* **Home:**
 * The homepage now pulls in the information from `config.json` to display links and information about the latest release.
 * We could easily detect what OS and Architecture (32/64) on the homepage as well and make the download button specific to the user.
* **Download:**
 * The download page will consume the `api.json` file to display an archive of download links for all major past versions.
 * It will also check against the `config.json` file to know what the current recommended release is.
 * On page load we detect your OS and architecture and automatically display the correct ( Windows | Linux | OSX ) and ( 32-bit | 64-bit ) selection depending on what your browser reports.
* **Quick Start:**
 * The quick start page has the original instructions that are useful for manually setting up your environment. It also has instructions for using `npm install`. These second instructions will work for all OS's identically.
 * There is a filter to switch between these two options.
 * They are stored in easy to maintain markdown files, as the rendered DOM produces very ugly markup due to the code highlighting.
* **Privacy:** A privacy page has been created with basic information that privacy conscious users may care about.

* * *

### Improvements for future versions

* Once hooked up properly using a CNAME and proper repo naming convention, the pages can be altered to use root level linking of files which will fix some fringe cases on the 404 router.
* Adding additional pages like:
 * "Showcase" or "Spotlight" to show apps that have been made with NW.js
 * "Tutorials" or "References" for links to NW.js specific videos, blogs, books, libraries, and frameworks.
 * "About" page. A few paragraphs about the people working on the project.
 * "History" page. A full history of the project, how it started and all the changes it's gone through along the way.
 * Hosted documentation. Rather than linking directly to the GitHub Wiki. We could put the most important FAQ's on the site, or find a way to use GitHub's API to pull in the wiki content and put it on the site dynamically.
* Explainer Video. This may do wonders to highlight exactly what NW.js is and how it's used for people who are coming to the site and just hearing about the project.
* Redesign of the Features section on the homepage. This area just feels like it could be improved.
* Redesign of the downloads sections of the homepage to highlight and focus on the download that is relevent to the user.
* Abstract out all English language text to a JSON file that is used to replace keywords in the markup with their approriate text. Then use that JSON file as a base for other translations.
* An automated build system could be put in place using Grunt or Gulp that would concat, minify, and uglify our javascript into one file.
* An automated way of generating the `api.json` file could be investigated to allow for faster updates that are less prone to error.
* Whoever created the original graphics work (presumably Daniel Cohen), could upload the source files (PSD/AI) to the design folder of the project to allow for better optimized artwork on the site.

### CODE REVIEW

**Comment by rogerwang** [comment]
Thanks for your effort @TheJaredWilcurt ! @ghostoy has been working on the new website as well. Please work with him.

btw, the logo is incorrect and we're not going to host the website on github.

**Comment by TheJaredWilcurt** [comment]
I've altered all images in this repo that were using Cohen's logo design to now have the original.

* [TheJaredWilcurt.github.io/website](http://thejaredwilcurt.github.io/website)

* * *

I've looked all over and see no indication that @ghostoy is working on this site.

* He hasn't forked this project.
* There are no branches for his version.
* Not a single commit across any of the branches are his.
* He has no public repos that relate to it.
* He hasn't commented on a single issue in this repo.
* There is no mention of this anywhere in this repo (such as in the README).
* I've not seen him in the chatroom talking about it.
* The nwjs.io website has a link stating "site under construction", but it doesn't link to any planning document, or a discussion about the project, or anything. It just links to the repo. And since the site has been in the same "coming soon" status for a year and the repo is open source, it implies that it's waiting on someone in the community to make the site. (So I did).

All I have to go off of is:

* **master** -  An ugly "Coming Soon" page that has been there for a year.
* **dev** - A semi-finished, well designed, branch that seems to have been abandoned 10 months ago, but from a design perspective was basically complete (just add code).
* **beta** - And a different branch that has one commit and looks like someone spent about an hour on it, saw the **dev** branch, and gave up.

* * *

**Is there an actual good reason not to host this on GitHub's servers?** They're explicitly designed for making sites for open-source projects. This site is ready to go live now. It's one button click away. It's got a good design, it's easy to update, and it's a huge improvement over what we have currently.

* * *

#### Benefits of using GitHub Pages:

* Users can simply browse the repo in their browser to edit a file and contribute rather than having to fork the entire repo, clone it down, edit the file, make a commit, push it up, make a pull request, and wait. Instead it's simply "edit" and "propose file change". Extremely easy and leads to allowing more people to help.
* Updates go live instantaneously.
* It's a standard most front end devs are familiar with.
* You are still able to link top-level-domains to the repo. For example:

GitHub URL | Site Repo | Top Level Domain
:--|:--|:--
[UniversalGUI.github.io](http://UniversalGUI.github.io)             | [github.com/UniversalGUI/UniversalGUI.github.io](http://github.com/UniversalGUI/UniversalGUI.github.io) | [UGUI.io](http://ugui.io)
[FLIF-hub.github.io](http://FLIF-hub.github.io)                     | [github.com/FLIF-hub/FLIF-hub.github.io](http://github.com/FLIF-hub/FLIF-hub.github.io)                 | [flif.info](http://flif.info)
[FLIF-hub.github.io/UGUI_FLIF](http://FLIF-hub.github.io/UGUI_FLIF) | [github.com/FLIF-hub/UGUI_FLIF](http://github.com/FLIF-hub/UGUI_FLIF)                                   | [flif.info/UGUI_FLIF](http://flif.info/UGUI_FLIF)

* Those doing more extensive work only need to download the repo, install node, and run one file to contribute.
* And it's free.

The only downside is you can't run server side scripts, but this site doesn't need them, and like won't ever need them, so that's not even relevant.

* * *

#### Downsides to running a server:

* Someone needs to spend time maintaining the server.
* Increased costs in order to have reliable uptime.
* Open Source community working on the site doesn't know what other code is running on the server.
* Increased complexity by having to create a system that attempts to mirror the GitHub repo.
* Increased complexity for those working on the site, as now they need to set up a development environment to match the server in order to contribute.

* * *

I can't see a situation in which the increased complexity and inconvenience of using an external server would outweigh the simplicity and reliability of letting the server storing the repo be the one to host the files, since it already is.

I think it's a waste of effort to go the external server route. I'm willing to forego common sense on this though, **so long as we can have an ACTUAL WEBSITE**. If using an external server is what it takes, sobeit.

* * *

I've taken days away from my own projects to help yours. Put in over 70 commits, about 3,000 lines of code, and wrote up a proposal document. It's very frustrating to be told "You should work with some guy who has done literally nothing on this project". I made the site. It's done. It's ready to go live. If he (or anyone else) wants to help, I've given a list of improvements to be made in the proposal above and in the README for this branch.

When is this going live?

**Comment by ghostoy** [comment]
@TheJaredWilcurt The reason to host website on our own server is that we need more controls on the website. And we also prefer to use static website just like Github pages, so that we can publish releases with Markdown. The solution is borrowed from Node.js, which is based on [Metalsmith](http://www.metalsmith.io/). We plan to get the new website online in this week. So the quick decision is to refactor the site from 'dev' branch with Matalsmith, React.js and SCSS. The new website is now in 'develop' branch. ('dev' and 'beta' may be dropped in future)

The new website lacks some features as you listed above, such as responsive. We still hope you can contribute your ideas based on the new website in 'develop' branch. And also I suggest you can split PR into individual features to make review easily.

List of interested ideas your PR included:

* Responsive
* Downloads page
* Favicons

And I like the plans you listed above. And I suggest you can join in the mailing list [nwjs-dev](https://groups.google.com/forum/#!forum/nwjs-dev) for discussion. For the document part, we are now hosting documents on http://docs.nwjs.io/. Please see the `docs` folder in nwjs/nw.js repo for details. The new website now points the documentation to this doc site.

**Comment by TheJaredWilcurt** [comment]
@rogerwang @ghostoy 

Because of MetalSmith requiring a newer version of Node.js, I can't work on this site on my work laptop. My job has a very specific development environment that requires an older version of Node.js. I don't have time to waste trying to set up another NVM knockoff for Windows. All it does is screw up my dev environment that I need to use for work and I end up wasting half a day trying to fix it. I'm rarely at home, and my home desktop is the only computer I have capable of running your site in it's current state.

I see absolutely no benefit in using MetalSmith. It looks as though the only reason it was picked is because Node uses it. If you are contributing to Node, it's not unreasonable to expect contributors to use the latest version of it. But if you are running *any other open source project*, placing arbitrary limitations and using more obscure technology only serves to limit the amount of people who want to help from being able to.

This is detrimental and cuts off willing contributors like myself. **In the same amount of days that it took me to redo the entire website, I've been able to change the [spacing in a few files](https://github.com/nwjs/website/pull/19)**. Whoop-de-doo. I don't have time to sit at home and work on the one computer I have access to with Node 5 to redo your whole website again. If I could do this on my laptop during my downtime your site would be getting a lot more pull requests for bug fixes and improvements.

I'm fine working with React, but again, this also seems like unnecessary additional levels of abstraction on a site that is too small and simple to justify a need for it.

I can see a purpose for hosting the site on your own server based on the docs subdomain. I can see a benefit for using Sass. But I've yet to see any compelling reason to use MetalSmith or React. Can someone defend these choices? Other than "I just wanted to make a site using React", or "That other site did it so it must be good". Are these up for debate? Because if not, I don't know if I'll be of much help. I want to help, please don't use technology that prevents me from being able to. I've been trying to work around it, but finding it incredibly difficult.

**Comment by rogerwang** [comment]
We don't have to use React or MetalSmith. We just needed it to be finished soon so we picked them up.

**Comment by TheJaredWilcurt** [comment]
Well that is a relief. Are there any alternatives you guys would prefer?

Previously I was implementing a very simple system by which JavaScript would piece together parts of a page from other components, like so:

    $.get("header.html", function (headerData) {
        $("header").html(headerData);
    });

This rather simplistic approach doesn't scale very well on a site with hundreds of pages, but works okay for a site with only 10 or 20. It also means that we can pull in markdown files and process them.

    $.get("home.md", function (homeData) {
        var homeHTML = marked(homeData);
        $("#content").html(homeHTML);
    });

These are very easy to understand and simple, though somewhat crude as well. I'm open to more refined systems. But preferably light weight options, or ones that don't over complicate such a small and simplistic website.

Rather than having the page built on load (as shown above), we could use a system like Require.js, Webpack, or Browserify, with Grunt or Gulp to combine these pieces ahead of time. Build them out to a pre-rendered version that gets deployed. Similar to what MetalSmith was attempting, but in a more common and standardized fashion. This requires more setup on our side, and would require more knowledge from our contributors, but doesn't require specific versions of Node to run, and would result in a site that produces fewer network requests than the above code samples.

**Comment by ghostoy** [comment]
@TheJaredWilcurt We are open to accept PRs to the website including switching to other toolchains. Just keep your PR simple, so that we can review and merge quickly.

**Pull request closed without merging**
